### ISSUE TITLE
can't resolve module

### ISSUE THREAD

**Issue by musab** [kinotto/node-typescript-webpack-starter#1]
I created a new file: 

```
src
      graphql
        types
          types.ts
```

the contents in types.ts: 
```
export const marge = "marge";
```

but when I try `import { marge } from "./graphql/types/types";` inside `index.ts` I get the following web pack error:

```
ERROR in ./src/index.ts
Module not found: Error: Can't resolve './graphql/types/types'
```

Any idea why?

**Comment by kinotto** [comment]
Hey @apollomusa ,
thanks for raising the issue,
actually the _webpack.config.js_ file was missing a rule to resolve all the modules othern than index.ts

```
resolve: {
    extensions: ['.ts']
 }
```

i've just pushed the [changes](https://github.com/kinotto/node-typescript-webpack-starter/commit/90a4959abe88a00805a2fc4ea8debc1081a9a3b5), if you pull you should be fine.

Thanks, have a good one :-)
